# -*- coding: utf-8 -*-
"""evaluate_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11BIlgwumflI-UUd32VgbQPkfjveCwcUN
"""

import os
import warnings
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image

import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.metrics import confusion_matrix, classification_report

warnings.filterwarnings("ignore")

# ============================================================================
# CONFIGURATION
# ============================================================================
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_DIR = os.path.join(BASE_DIR, "data", "FloodingDataset2")
PROCESSED_DIR = os.path.join(DATASET_DIR, "processed_data", "binary")
TEST_DIR = os.path.join(PROCESSED_DIR, "test")
MODEL_DIR = os.path.join(BASE_DIR, "models")

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

efficientnet_b0 = "efficientnet_b0.keras" #"binary_flood_final_20260114_030603.keras"
resnet_50 = "resnet50.keras" #"binary_resnet50_final_resume_20260119_190703.keras"
hmm_efficientnet_b0 = "hnm_efficientnet_b0.keras" #"binary_flood_hnm_final_20260120_024721.keras"

models = {
    "efficientnet_b0": efficientnet_b0,
    "resnet_50": resnet_50,
    "hmm_efficientnet_b0": hmm_efficientnet_b0,
}
#SELECT MODEL HERE
SELECTED_MODEL = "hmm_efficientnet_b0"

# ============================================================================
# LOAD MODEL
# ============================================================================

model_path = os.path.join(MODEL_DIR, models[SELECTED_MODEL])

if not os.path.exists(model_path):
    raise FileNotFoundError(f"Model not found: {model_path}")

print(f"Loading model: {SELECTED_MODEL}")
model = load_model(model_path)

# ============================================================================
# LOAD TEST DATA
# ============================================================================

test_datagen = ImageDataGenerator(rescale=1.0 / 255)

test_generator = test_datagen.flow_from_directory(
    TEST_DIR,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False,
)

y_true = test_generator.classes
class_names = list(test_generator.class_indices.keys())

# ============================================================================
# EVALUATION
# ============================================================================

y_pred_proba = model.predict(test_generator, verbose=1)
y_pred = (y_pred_proba > 0.5).astype(int).flatten()

test_loss, test_acc, test_precision, test_recall, test_auc = model.evaluate(
    test_generator, verbose=0
)

test_f1 = (
    2 * (test_precision * test_recall) / (test_precision + test_recall)
    if (test_precision + test_recall) > 0
    else 0
)

print("\nTest Results")
print(f"Accuracy:  {test_acc:.4f}")
print(f"Precision: {test_precision:.4f}")
print(f"Recall:    {test_recall:.4f}")
print(f"F1-score:  {test_f1:.4f}")
print(f"AUC:       {test_auc:.4f}")

# ============================================================================
# CONFUSION MATRIX
# ============================================================================

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names,
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title(f"Confusion Matrix – {SELECTED_MODEL}")
plt.tight_layout()
plt.show()

print("\nClassification Report")
print(classification_report(y_true, y_pred, target_names=class_names))

# ============================================================================
# SWIMMING POOL ANALYSIS
# ============================================================================

test_files = test_generator.filenames
swimming_pool_idx = [i for i, f in enumerate(test_files) if "Swimmingpool" in f]

if swimming_pool_idx:
    sp_preds = y_pred[swimming_pool_idx]
    sp_true = y_true[swimming_pool_idx]

    errors = np.sum(sp_preds != sp_true)
    fp = np.sum((sp_preds == 0) & (sp_true == 1))

    print("\nSwimming Pool Analysis")
    print(f"Total images: {len(swimming_pool_idx)}")
    print(f"Misclassified: {errors}")
    print(f"False positives: {fp}")
else:
    print("\nNo swimming pool images found.")

print("\nEvaluation complete.")
